name: Create and Merge Pull Request

on:
  push:
    branches:
      - fix/date-handling

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
          
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Merge fix/date-handling into main"
          title: "Fix date handling in HomePage and firebase service"
          body: |
            This PR fixes the date handling issues in the HomePage component and firebase service.
            
            Changes made:
            - Updated Entry and Vote interfaces to use Date instead of Timestamp
            - Modified createEntry function to properly convert between Firestore Timestamp and JavaScript Date objects
            - Updated all entry retrieval functions to use safelyConvertToDate helper
            - Simplified date handling in HomePage component
          branch: main
          delete-branch: false
          labels: |
            bug
            enhancement
          draft: false
          token: ${{ secrets.GH_PAT }}
          
      - name: Get Pull Request URL
        run: |
          echo "Pull Request URL: ${{ steps.create-pr.outputs.pull-request-url }}"
          
      - name: Wait for Pull Request
        run: |
          echo "Waiting for pull request to be created..."
          sleep 10
          
      - name: List Pull Requests
        run: |
          echo "Listing all pull requests..."
          gh pr list --json number,title,url,state
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          
      - name: Merge Pull Request
        run: |
          PR_URL="${{ steps.create-pr.outputs.pull-request-url }}"
          if [ -n "$PR_URL" ]; then
            PR_NUMBER=$(echo $PR_URL | grep -o '[0-9]*$')
            echo "Merging pull request #$PR_NUMBER"
            gh pr merge $PR_NUMBER --squash --delete-branch=false
          else
            echo "No pull request URL found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }} 