name: Create and Merge Pull Request

on:
  push:
    branches:
      - fix/date-handling

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
          
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Merge fix/date-handling into main"
          title: "Fix date handling in HomePage and firebase service"
          body: |
            This PR fixes the date handling issues in the HomePage component and firebase service.
            
            Changes made:
            - Updated Entry and Vote interfaces to use Date instead of Timestamp
            - Modified createEntry function to properly convert between Firestore Timestamp and JavaScript Date objects
            - Updated all entry retrieval functions to use safelyConvertToDate helper
            - Simplified date handling in HomePage component
          branch: main
          delete-branch: false
          labels: |
            bug
            enhancement
          draft: false
          token: ${{ secrets.GH_PAT }}
          
      - name: Get Pull Request URL
        run: |
          echo "Pull Request URL: ${{ steps.create-pr.outputs.pull-request-url }}"
          
      - name: Wait for Pull Request
        run: |
          echo "Waiting for pull request to be created..."
          sleep 10
          
      - name: Enable auto-merge for Pull Requests
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "false"
          MERGE_COMMIT_MESSAGE: "Merge fix/date-handling into main"
          PR_BRANCH: "fix/date-handling"
          PR_TITLE: "Fix date handling in HomePage and firebase service" 