name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - development
      - feature/phase-dynamics
  pull_request:
    branches:
      - main
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd frontend
          npm ci

      - name: Create .env file
        run: |
          cd frontend
          echo "VITE_API_URL=https://benpomme.github.io/projectCP/api" > .env
          echo "VITE_FIREBASE_API_KEY=AIzaSyBqeebps7CNCQw_xis2DKiGHMRYmurj_B4" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=kingcp-a0065.firebaseapp.com" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=kingcp-a0065" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=kingcp-a0065.firebasestorage.app" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=550768863932" >> .env
          echo "VITE_FIREBASE_APP_ID=1:550768863932:web:acabd2d2584b8165a7beb9" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=G-QRVT5F6VGR" >> .env
          echo "VITE_GOOGLE_CLIENT_ID=123456789012-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com" >> .env
          echo "VITE_APP_ENV=production" >> .env

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages
          commit_message: ${{ github.event.head_commit.message }}

      # Add fallback manual deployment if the above fails
      - name: Deploy to GitHub Pages (fallback)
        if: ${{ failure() }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./frontend/dist
          branch: gh-pages 