name: Update Firebase Storage CORS Settings

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Create CORS configuration file
        run: |
          cat > cors.json << EOL
          [
            {
              "origin": ["https://benpomme.github.io"],
              "method": ["GET", "POST", "PUT", "DELETE", "HEAD"],
              "maxAgeSeconds": 3600,
              "responseHeader": ["Content-Type", "Content-Disposition", "Content-Length"]
            }
          ]
          EOL
          
      - name: Update Firebase Storage CORS settings
        run: firebase storage:cors update cors.json --project kingcp-a0065 --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Cleanup
        run: rm cors.json 